wildfly-security/elytron-subsystem

src/main/resources/schema/wildfly-elytron_1_0.xsd

XSD schema fixed to be conform with examples and tests.
(To ensure green validation result of examples reorder of tags in examples or #140 required.)
* maxOccures of element in `<properties>` and similar should be unbounded
* mispelled name (htt vs http)
* probably old names of attributes (post-realm-rewriter vs post-realm-**name**-rewriter, operation vs **logical-**operation)

XSD schema fixed by parser/examples

---

pom.xml
src/main/resources/subsystem-templates/elytron-empty.xml
src/main/resources/subsystem-templates/elytron-main.xml
src/main/resources/subsystem-templates/elytron-web-main.xml

I have created new profile (`-Pinstall2wildfly-core`) which will install necessary modules and extension to wildfly-core which lays in -Dwildfly.core.home. After creating module.zip file target/module directory is set back to original build state.
Added modules use GAV to find artifact, so it is enough to build them locally and user proper GAV (see pom.xml). 
Example of usage: 
`mvn clean install -Pinstall2wildfly-core -Dwildfly.core.home=$HOME/wildfly-core/core/dist/target/wildfly-core-3.0.0.Alpha1-SNAPSHOT`

New profile to maven build which can install subsystem to wildfly-core

---

pom.xml
src/main/java/org/wildfly/extension/elytron/Capabilities.java
src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
src/main/java/org/wildfly/extension/elytron/DirContextParser.java
src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser.java
src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/RealmParser.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
src/test/resources/org/wildfly/extension/elytron/realms-test.xml
src/test/resources/org/wildfly/extension/elytron/security-realms.xml

* DirContext definition in subsystem from LDAP realm to standalone block
* Allowed principal+password omitting (for AUTHENTICATION_LEVEL="none")
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/485

[ELY-462] DirContext definition outside of realms

---

src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/java/org/wildfly/extension/elytron/TlsParser.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
src/test/resources/org/wildfly/extension/elytron/tls-test.xml
src/test/resources/org/wildfly/extension/elytron/tls.xml

Related to https://issues.jboss.org/browse/ELY-643 / https://github.com/wildfly-security/elytron-subsystem/issues/239
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/499

[WFLY-4351] Resolves #239 Export setUserCipherSuiteOrder on SSLContext resource

---

src/main/java/org/wildfly/extension/elytron/MapperParser.java
src/main/java/org/wildfly/extension/elytron/RealmMapperDefinitions.java
src/main/java/org/wildfly/extension/elytron/RegexAttributeDefinitions.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
src/test/resources/org/wildfly/extension/elytron/domain.xml
src/test/resources/org/wildfly/extension/elytron/mappers.xml

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7224

[WFLY-7224] Missing validation check for simple-regex-realm-mapper and mapped-regex-realm-mapper in Elytron subsystem.

---

src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7254

[WFLY-7254] pattern-filter disappears if predefined-filter is used for configurable-sasl-server-factory in Elytron subsystem

---

src/main/resources/module/main/module.xml

The LDAP context creation use (in JDK) reflection to obtain LdapCtxFactory.
(In most cases was working because it was loaded using "org.wildfly.extension.elytron:main" module classloader)
https://issues.jboss.org/browse/WFLY-7278

[WFLY-7278] Added sun.jdk into module.xml

---

src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java
src/main/java/org/wildfly/extension/elytron/TlsParser.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties

Change suggested by Martin Chroma: new-item-* attributes should be enclosed in OBJECT.
This modify model to have the same structure as the XML already has.

[WFLY-7314] LdapKeyStore - new-item-template object

---

src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/ldap.xml

https://issues.jboss.org/browse/WFLY-7320
Related to https://github.com/wildfly-security/wildfly-elytron/pull/510
Added filter-name similar to filter-alias in LdapKeyStore. Required to support referrals:
`filter-name="(|(uid={0})(objectclass=referral))"`

[WFLY-7320] adding ldap-realm.filter-name (need for referrals)

---

src/main/resources/schema/wildfly-elytron_1_0.xsd

WildFly: https://issues.jboss.org/browse/WFLY-7154

[WFLY-7154] poor description of session-timeout,maximum-session-cache-size attributes.

---

src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7288
Note: All attributes (algorithm-from, hash-from, seed-from, sequence-from) from otp-credential-mapper are already "nillable" => false and no changes are needed.

[WFLY-7288] Elytron - inconsistency between DMR and XSD representation of ldap-realm

---

src/main/resources/schema/wildfly-elytron_1_0.xsd

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7285

[WFLY-7285] Elytron - inconsistency between DMR and XSD representation of simple-permission-mapper

---

src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
src/main/java/org/wildfly/extension/elytron/DirContextParser.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/ldap.xml

https://issues.jboss.org/browse/WFLY-7473
(no wildfly-elytron dependency)
* dir-context - adding connection-timeout, read-timeout
* refactoring of DirContextParser to use PersistentResourceXMLDescription

[WFLY-7473] dir-context - adding connection-timeout, read-timeout

---

src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7146 (reopened)

[WFLY-7146](reopened) Elytron, regex-name-validating-rewriter - 'match' attribute required and unclear description

---

src/main/java/org/wildfly/extension/elytron/MapperParser.java
src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java

https://issues.jboss.org/browse/WFLY-7491
* removed from required in parser
* allowed zero-length (blank delimiter) (applied to x500-attribute-principal-decoder too)

[WFLY-7491] concatenating-principal-decoder - joiner optional

---

src/main/java/org/wildfly/extension/elytron/CertificateChainAttributeDefinitions.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/SSLContextResource.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/java/org/wildfly/extension/elytron/SSLSessionDefinition.java
src/test/java/org/wildfly/extension/elytron/TlsTestCase.java

https://issues.jboss.org/browse/WFLY-7175
* CertificateChainAttributeDefinitions: flattened model as requested by WFLY-7175
* Other: Fixes of ssl-session resource (information about side (client/server) need to be passed to SSLSession resource)
* covered by tests

[WFLY-7175] ssl-session resource flattening and fixes

---

src/main/java/org/wildfly/extension/elytron/DomainService.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7589

[WFLY-7589] Wrong description for injecting the same realm to Elytron security-domain in CLI

---

pom.xml
src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java

There is wildfly-core version bump included as I need the newest API for CredentialReference.
resolves: https://github.com/wildfly-security/elytron-subsystem/issues/285

Issue #285 use Credential Store Client Util from Credential Store resource definition

---

src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java

Issue: https://issues.jboss.org/browse/WFLY-7665

WFLY-7665: fix writeAttribute definition for LDAP keystore

---

src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/MapperParser.java
src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/domain-test.xml

Depends on https://github.com/wildfly-security/wildfly-elytron/pull/550
https://issues.jboss.org/browse/WFLY-7176
Note: OID+ATTRIBUTE_NAME should be set as require when will be WFCORE-1556 resolved:
http://wildfly-development.1055759.n5.nabble.com/Fixing-handling-of-required-attributes-with-alternatives-td5717450.html
UPDATE: or do you think it woul be better one attribute "attribute", which would combine OID+ATTRIBUTE_NAME ?

[WFLY-7176] x500-attribute-principal-decoder - names instead of OIDs

---

src/main/java/org/wildfly/extension/elytron/ProviderLoaderService.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7829

[WFLY-7829] Coverity: wrong condition in ProviderLoaderService.unregisterProviders (Elytron subsystem)

---

src/main/java/org/wildfly/extension/elytron/AggregateComponentDefinition.java
src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java
src/main/java/org/wildfly/extension/elytron/CertificateChainAttributeDefinitions.java
src/main/java/org/wildfly/extension/elytron/ClassLoadingAttributeDefinitions.java
src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java
src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java
src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/RealmDefinitions.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java

Resolve build warning:
* Type conversions
* setAllowNull() deprecated in controller API replaced by setRequired()

Resolve deprecated API call, build warnings

---

src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7681 (reopen)

[WFLY-7681] (reopen) Unify descriptions of mechanism-provider-filtering-sasl-server-factory of XSD and DMR

---

src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7831

[WFLY-7831] Coverity: default platform encoding used in TokenRealmDefinition (Elytron subsystem)

---

src/main/java/org/wildfly/extension/elytron/CachingRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/RealmParser.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/security-realms.xml

I also have some changes in the queue based on https://github.com/wildfly-security/wildfly-elytron/pull/632. The change will include a ```maximum-age``` attribute to the ```caching-realm```.

Resolves #370 Add support for caching realms

---

src/main/java/org/wildfly/extension/elytron/ClassLoadingAttributeDefinitions.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7832

[WFLY-7832] Coverity: dereference null value in ClassLoadingAttributeDefinitions (Elytron subsystem)

---

src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/resources/schema/wildfly-elytron_1_0.xsd

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7653

[WFLY-7653] Validate session-timeout and maximum-session-cache-size to be non-negative

---

src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
src/test/resources/org/wildfly/extension/elytron/ldap-data.ldif
src/test/resources/org/wildfly/extension/elytron/ldap-referred.ldif

LDAP referrals tests improvement - using two standalone LDAP servers now.
Green tests require https://github.com/wildfly-security/wildfly-elytron/pull/637
https://issues.jboss.org/browse/WFLY-7705

[WFLY-7705] LdapRealm referrals tests

---

src/main/resources/schema/wildfly-elytron_1_0.xsd

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7653
Corrected the missing check in XSD for clientSSLContextType.

[WFLY-7653] (Reopen) Validate session-timeout and maximum-session-cache-size to be non-negative

---

src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7833

[WFLY-7833] Coverity: dereference null value in PermissionMapperDefinitions (Elytron subsystem)

---

src/main/java/org/wildfly/extension/elytron/KeyStoreService.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-8104

[WFLY-8104] Coverity static analysis, Dereference after null check, KeyStoreService (elytron-subsystem)

---

src/main/java/org/wildfly/extension/elytron/KeyStoreService.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-8103

[WFLY-8103] Coverity static analysis, Dereference after null check, KeyStoreService (elytron-subsystem)

---

src/main/resources/schema/wildfly-elytron_1_0.xsd

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-8235

[WFLY-8235] Wrong type of Elytron match-no-user in XSD

---

src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java

https://issues.jboss.org/browse/WFLY-7843
Fix of "Configured property is parsed also with quotation marks." (actually ModelNode of type STRING passed instead of String)

[WFLY-7843] DirContext evironment properties fix
