wildfly-security/elytron-subsystem

src/main/java/org/wildfly/extension/elytron/Capabilities.java
src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/JdbcRealmService.java
src/main/java/org/wildfly/extension/elytron/RealmParser.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/ElytronSubsystemUtil.java
src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java
src/test/resources/org/wildfly/extension/elytron/security-realms.xml

Build is failing for this PR. The reason is that I need to figure out how to avoid error due to unavailable capabilities required for our services. The ```JdbcRealmService``` requires the ```DataSource``` API.
I've done some functional testing connecting to a running database to authenticate users. Everything seems to work so far. Specially the capabilities related code.

[ISSUE-46] - Jdbc Realm Definitions.

---

src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/RealmParser.java

@darranl I totally missied this commit. Sorry for the inconvenience !

Fixes #46 Renaming constant and method names to match ObjectDefinition.

---

src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/FileSystemRealmService.java
src/main/java/org/wildfly/extension/elytron/RealmParser.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java
src/test/resources/org/wildfly/extension/elytron/security-realms.xml

Resolves https://github.com/wildfly-security/elytron-subsystem/issues/73 (I am not sure if this should be linked differently)

Filesystem realm

---

src/main/resources/schema/wildfly-elytron_1_0.xsd

Suggestion to allow different order of tags in elytron subsystem configuration.
Notices to individiual replacements would be ideal in comment to given line.

Elytron XSD schema - order independent

---

README.md

Adding reference where capabilities and requirements has to referenced.

Adding CaR doc reference to readme file

---

pom.xml
src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
src/main/java/org/wildfly/extension/elytron/DomainParser.java
src/main/java/org/wildfly/extension/elytron/DomainService.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd

Depends on https://github.com/wildfly-security/wildfly-elytron/pull/409

Resolves #174 Add the ability to specify the domains that are trusted by a particular domain

---

src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/MapperParser.java
src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
src/test/resources/org/wildfly/extension/elytron/domain-test.xml
src/test/resources/org/wildfly/extension/elytron/filesystem-realm/j/s/jsmith@example.redhat.com.xml
src/test/resources/org/wildfly/extension/elytron/mappers.xml
src/test/resources/org/wildfly/extension/elytron/testingrealm1-users.properties

Depends on https://github.com/wildfly-security/wildfly-elytron/pull/432

[ELY-221] X.500 principal mapper improvements

---

pom.xml
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/RealmParser.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/LdapService.java
src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
src/test/resources/org/wildfly/extension/elytron/ldap.ldif
src/test/resources/org/wildfly/extension/elytron/realms-test.xml
src/test/resources/org/wildfly/extension/elytron/security-realms.xml

**Ldap security realm**
* First commit:
* Added testing with ApacheDS server (like in wildfly-elytron)
* Second commit:
* Added ldap realm attributes specific to the modifiability
* Added credential loaders/persisters
* Unified modifiability test - across all modifiable realms (filesystem+ldap only for now)
~~Successful tests depends on https://github.com/wildfly-security/wildfly-elytron/pull/461~~
Successful tests depends on https://github.com/wildfly-security/wildfly-elytron/pull/463

LdapRealm - testing with ApacheDS + configuration (attributes, loaders, persisters)

---

pom.xml
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/mappers.xml

Automatic validation of all subsystem config XMLs against XSD schema on on build + fixes of found problems.

XSD auto-validation

---

src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/java/org/wildfly/extension/elytron/TlsParser.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/tls-test.xml
src/test/resources/org/wildfly/extension/elytron/tls.xml

* fixing support of **provider-loader** of key/trust-manager
* adding support of **provider** of key/trust-manager

[WFLY-7073] provider-loader + provider of key/trust-manager

---

src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd

RealmMappers resources descriptions fixed by bug reports:
* https://issues.jboss.org/browse/WFLY-7065
* https://issues.jboss.org/browse/WFLY-7066

[WFLY-7065][WFLY-7066] RealmMappers descriptions fixes

---

src/main/java/org/wildfly/extension/elytron/MapperParser.java
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/domain.xml
src/test/resources/org/wildfly/extension/elytron/mappers.xml

https://issues.jboss.org/browse/WFLY-7097

[WFLY-7097] constant-role-mapper - roles with space

---

src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
src/test/resources/org/wildfly/extension/elytron/domain-test.xml

https://issues.jboss.org/browse/WFLY-7071

[WFLY-7071] default-realm in realms checking

---

src/main/java/org/wildfly/extension/elytron/CertificateChainAttributeDefinitions.java
src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
src/main/java/org/wildfly/extension/elytron/ProviderAttributeDefinition.java
src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java

https://issues.jboss.org/browse/WFLY-7103

[WFLY-7103] Domain - list/items attribute requirement

---

src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/RealmParser.java
src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
src/test/resources/org/wildfly/extension/elytron/realms-test.xml
src/test/resources/org/wildfly/extension/elytron/security-realms.xml

It depends on https://github.com/wildfly-security/elytron-subsystem/pull/210.
@darranl it also depends on that change to Elytron module in Wildfly Core (javax.json.api).
The only commit related with the issue is https://github.com/wildfly-security/elytron-subsystem/pull/219/commits/2e8f6037687dbb50476e1598ce3cde4ab586c220.

Resolves #216 Add Token-based realm

---

src/main/resources/schema/wildfly-elytron_1_0.xsd

https://issues.jboss.org/browse/WFLY-7145

[WFLY-7145] removing key-store atttribute read-only

---

README.md

Added basic installation instructions.

README - installation instructions

---

src/main/java/org/wildfly/extension/elytron/NameRewriterDefinitions.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd

https://issues.jboss.org/browse/WFLY-7146

[WFLY-7146] regex-name-validating-rewriter fix

---

src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/MapperParser.java
src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/main/resources/subsystem-templates/elytron.xml
src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
src/test/resources/org/wildfly/extension/elytron/domain-test.xml
src/test/resources/org/wildfly/extension/elytron/mappers.xml

https://issues.jboss.org/browse/WFLY-7143
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/496

[WFLY-7143] constant-permission-mapper

---

src/main/java/org/wildfly/extension/elytron/FilteringKeyStoreDefinition.java

https://issues.jboss.org/browse/WFLY-7162

[WFLY-7162] filtering-key-store:write-attribute fix

---

src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/java/org/wildfly/extension/elytron/TlsParser.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/tls-test.xml
src/test/resources/org/wildfly/extension/elytron/tls.xml

https://issues.jboss.org/browse/WFLY-7194

[WFLY-7194] key-manager: password to key-password, required

---

src/main/java/org/wildfly/extension/elytron/NameRewriterDefinitions.java
src/test/resources/org/wildfly/extension/elytron/mappers.xml

https://issues.jboss.org/browse/WFLY-7203

[WFLY-7203] regex-name-validating-rewriter - match optional

---

src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
src/main/java/org/wildfly/extension/elytron/FilteringKeyStoreDefinition.java
src/main/java/org/wildfly/extension/elytron/RealmMapperDefinitions.java
src/main/resources/schema/wildfly-elytron_1_0.xsd

Setting attributes as required:
#242 
https://issues.jboss.org/browse/WFLY-7226
https://issues.jboss.org/browse/WFLY-7191

[WFLY-7226][WFLY-7191] Resolves #242 - required attributes

---

src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java

https://issues.jboss.org/browse/WFLY-7149

[ELY-645] - unable to remove elytron subsystem

---

src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/MapperParser.java
src/main/java/org/wildfly/extension/elytron/RoleDecoderDefinitions.java
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/domain.xml
src/test/resources/org/wildfly/extension/elytron/mappers.xml

https://issues.jboss.org/browse/WFLY-7178

[WFLY-7178] removed empty-role-decoder

---

src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java

https://issues.jboss.org/browse/WFLY-7255

[WFLY-7255] ldap-realm attributes default

---

src/main/java/org/wildfly/extension/elytron/FileAttributeDefinitions.java
src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java

https://issues.jboss.org/browse/WFLY-7172

[WFLY-7172] PropertyRealm - path nillable, relative-to without expressions

---

src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java

https://issues.jboss.org/browse/WFLY-7219
Based on https://github.com/wildfly-security/elytron-subsystem/pull/230
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/496

[WFLY-7219] permission-mapper - create permission error handling

---

src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
src/test/resources/org/wildfly/extension/elytron/tls-test.xml

https://issues.jboss.org/browse/WFLY-7137

[WFLY-7137] KeyStore attribute "required" fix

---

src/main/resources/schema/wildfly-elytron_1_0.xsd

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7271

[WFLY-7271] Review elytron jdbc-realm resource XSD definition

---

src/main/java/org/wildfly/extension/elytron/DirContextParser.java
src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java
src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java

https://issues.jboss.org/browse/WFLY-7314

[WFLY-7314] LdapKeyStore + DirContext attributes definition fix

---

pom.xml
src/main/java/org/wildfly/extension/elytron/FilteringKeyStoreService.java
src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
src/test/resources/logging.properties

https://issues.jboss.org/browse/WFLY-7193
Related (but does not depend) to https://github.com/wildfly-security/wildfly-elytron/pull/502

[WFLY-7193] SSL logging

---

src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/test/resources/org/wildfly/extension/elytron/ldap.xml
src/test/resources/org/wildfly/extension/elytron/tls-test.xml
src/test/resources/org/wildfly/extension/elytron/tls.xml

https://issues.jboss.org/browse/WFLY-7301
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/508

[WFLY-7301] standard SSL protocols names

---

src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/LdapTestCase.java
src/test/resources/org/wildfly/extension/elytron/ldap.ldif
src/test/resources/org/wildfly/extension/elytron/ldap.xml

Based on https://github.com/wildfly-security/elytron-subsystem/pull/264
Related to https://github.com/wildfly-security/wildfly-elytron/pull/513 [ELY-669]
https://issues.jboss.org/browse/WFLY-7325
* Tests of referrals (in follow mode)
* Added missing XSD definition
* Accepting referrals mode in lowercase (as in JDK env property are)

[WFLY-7325] LDAP realm - referrals tests and fixes

---

src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
src/main/resources/schema/wildfly-elytron_1_0.xsd

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7272

[WFLY-7272] Elytron attribute-mapping index validation

---

src/main/java/org/wildfly/extension/elytron/KeyStoreResource.java

https://issues.jboss.org/browse/WFLY-7289

[WFLY-7289] ldap-key-store alias resource error handling

---

src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd

https://issues.jboss.org/browse/WFLY-7317

[WFLY-7317] DMR XSD inconsistency fixes

---

src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
src/main/resources/schema/wildfly-elytron_1_0.xsd

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7268

[WFLY-7268] Elytron jdbc-realm *-index attributes validation

---

src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7286

[WFLY-7286] Elytron - inconsistency between DMR and XSD representation of mechanism-provider-filtering-sasl-server-factory

---

src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7436

[WFLY-7436] Some attributes in Elytron ldap-realm are nillable=false but have set default values

---

src/test/java/org/wildfly/extension/elytron/SaslTestCase.java
src/test/resources/org/wildfly/extension/elytron/sasl-test.xml

Depends on https://github.com/wildfly-security/wildfly-elytron/pull/528
https://issues.jboss.org/browse/WFLY-7349

[WFLY-7349] Subsystem tests of SASL server factories

---

src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/LdapTestCase.java
src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
src/test/resources/org/wildfly/extension/elytron/ldap-data.ldif
src/test/resources/org/wildfly/extension/elytron/ldap-schemas.ldif
src/test/resources/org/wildfly/extension/elytron/ldap.xml
src/test/resources/org/wildfly/extension/elytron/scarab.pem

https://issues.jboss.org/browse/WFLY-7505
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/503

[WFLY-7505] LdapRealm - X509 credential

---

src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java

Depends on https://github.com/wildfly-security/wildfly-elytron/pull/543
https://issues.jboss.org/browse/WFLY-7476

[WFLY-7476] properties-realm error messages

---

src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7477

[WFLY-7477] Elytron dir-context not updatable

---

src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java

https://issues.jboss.org/browse/WFLY-7504

[WFLY-7504] jdbc-realm - principal-query null check

---

src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java

https://issues.jboss.org/browse/WFLY-7619

[WFLY-7619] CredentialStore removing fix

---

src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java

https://issues.jboss.org/browse/WFLY-7501

[WFLY-7501] Security domain should not have itself in trusted domains

---

src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java

Fix of first problem: using model.get(...) instead of DEFINITION.resolveModelAttribute(context, model)
The second will have to be resolved in CLI parser probably.
(+simplified)
https://issues.jboss.org/browse/WFLY-7437

[WFLY-7437] ldap-realm credential mappers fix+clearing

---

src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
src/test/resources/org/wildfly/extension/elytron/ldap.xml

https://issues.jboss.org/browse/WFLY-7587
(no elytron PR dependency)

[WFLY-7587] dir-context - referral-mode validation

---

src/main/java/org/wildfly/extension/elytron/CredentialStoreAliasDefinition.java
src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
src/test/java/org/wildfly/extension/elytron/CredentialStoreUtility.java
src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
src/test/resources/org/wildfly/extension/elytron/tls-test.xml

Changes necessary for https://github.com/wildfly-security/wildfly-elytron/pull/594 to work with subsystem.
There will be follow-up PR which will further utilize changes to the Credential Store API.

[ELY-810] initial changes for new Credential Store API

---

src/main/java/org/wildfly/extension/elytron/CredentialStoreAliasDefinition.java
src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
src/test/java/org/wildfly/extension/elytron/CredentialStoreUtility.java
src/test/resources/org/wildfly/extension/elytron/tls-test.xml

Good to merge with Elytron 1.1.0.Beta18. It has external flush() method at CredentialStore.

post ELY-810 and ELY-813 changes

---

src/main/java/org/wildfly/extension/elytron/AuthenticationFactoryDefinitions.java
src/main/java/org/wildfly/extension/elytron/ClassLoadingAttributeDefinitions.java
src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
src/main/java/org/wildfly/extension/elytron/FilteringKeyStoreDefinition.java
src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java
src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/ProviderAttributeDefinition.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java

https://issues.jboss.org/browse/WFLY-7574
(no subsystem part)

[WFLY-7574] expressions disabling in attributes

---

src/main/resources/schema/wildfly-elytron_1_0.xsd

https://issues.jboss.org/browse/WFLY-7491
(no subsystem part)

[WFLY-7491] concatenating-principal-decoder - XSD fix

---

src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7681

[WFLY-7681] Unify descriptions of mechanism-provider-filtering-sasl-server-factory of XSD and DMR

---

src/main/java/org/wildfly/extension/elytron/CommonAttributes.java
src/main/java/org/wildfly/extension/elytron/CustomComponentDefinition.java
src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java
src/main/java/org/wildfly/extension/elytron/RealmMapperDefinitions.java
src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java
src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7499

[WFLY-7499] Elytron "expressions-allowed" => false attributes

---

src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java

https://issues.jboss.org/browse/WFLY-7840

[WFLY-7840] authentication-context/match-rules allow null

---

src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7677

[WFLY-7677] Missing validation for write-attribute operation for introspection-url from Elytron token-realm

---

src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7830

[WFLY-7830] Coverity: Logically dead code in PermissionMapperDefinitions (Elytron subsystem)

---

src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/ldap.xml

https://issues.jboss.org/browse/WFLY-7720
(no elytron PR dependency)

[WFLY-7720] Expose dir-context connection properties

---

src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/ldap.xml

https://issues.jboss.org/browse/WFLY-7866
Elytron part: https://github.com/wildfly-security/wildfly-elytron/pull/615

[WFLY-7866] LdapRealm - allow-blank-password

---

src/main/java/org/wildfly/extension/elytron/ProviderLoaderService.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7828

[WFLY-7828] Coverity static analysis: Resource leaks in ProviderLoaderService (Elytron subsystem)

---

.travis-settings.xml
.travis.yml

To resolve delayed synchronization of (Elytron) bits from repository.jboss.org to Maven Central.

Added custom settings.xml to referrence JBoss Maven repository

---

src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/LdapTestCase.java
src/test/resources/org/wildfly/extension/elytron/ldap-data.ldif
src/test/resources/org/wildfly/extension/elytron/ldap.xml

https://issues.jboss.org/browse/WFLY-7897
Subsystem part of https://github.com/wildfly-security/wildfly-elytron/pull/629

[WFLY-7897] LdapRealm - Fix of {0} filtered attribute wildcard

---

src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/java/org/wildfly/extension/elytron/TlsParser.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/tls-test.xml
src/test/resources/org/wildfly/extension/elytron/tls.xml

https://issues.jboss.org/browse/WFLY-7153

[WFLY-7153] ssl-context - provider-loader, provider

---

src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java
src/main/java/org/wildfly/extension/elytron/AuthenticationClientParser.java
src/main/java/org/wildfly/extension/elytron/CredentialStoreParser.java
src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/java/org/wildfly/extension/elytron/TlsParser.java

this can be merged when upgraded to wildfly-core 3.0.0.Alpha19

post [WFCORE-2168] changes applied to elytron subsystem

---

src/main/java/org/wildfly/extension/elytron/CachingRealmDefinition.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/security-realms.xml

Depends on latest changes to Wildfly Elytron. Specially https://github.com/wildfly-security/wildfly-elytron/pull/632.

Resolves #370 Adding the maximum-age attribute to caching-realm

---

src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7575

[WFLY-7575] Elytron mechanism-provider-filtering-sasl-server-factory cannot be added without filters attribute in CLI

---

src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7977

[WFLY-7977] Synchronize XSD and DMR description of obtain-kerberos-ticket attribute

---

src/main/resources/subsystem-templates/elytron.xml

https://issues.jboss.org/browse/WFLY-7996

[WFLY-7996] Default XML config - local auth for ApplicationRealm

---

src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
src/main/java/org/wildfly/extension/elytron/DomainParser.java
src/main/java/org/wildfly/extension/elytron/DomainService.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/domain.xml

This is the subsystem side of https://github.com/wildfly-security/wildfly-elytron/pull/645

Issue#399 Automatic Identity Outflow

---

src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/LdapTestCase.java
src/test/resources/org/wildfly/extension/elytron/ldap.xml

https://issues.jboss.org/browse/WFLY-7844
Depends on: https://github.com/wildfly-security/wildfly-elytron/pull/644

[WFLY-7844] AuthenticationContext in DirContext

---

src/main/java/org/wildfly/extension/elytron/CredentialStoreParser.java
src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd

There is API change required. It has to be merged when Elytron 1.1.0.Beta25 will be used.

[ELY-916] inject Provider[] inside CredentialStore to instantiate custom objects

---

src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/java/org/wildfly/extension/elytron/TlsParser.java
src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/resources/org/wildfly/extension/elytron/tls-test.xml
src/test/resources/org/wildfly/extension/elytron/tls.xml

Depends on https://github.com/wildfly-security/wildfly-elytron/pull/640.

Resolves #387 Add support for CRL to trust managers

---

src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
src/test/resources/logging.properties
src/test/resources/org/wildfly/extension/elytron/ldap-data.ldif
src/test/resources/org/wildfly/extension/elytron/ldap-referred.ldif

Depends on https://github.com/wildfly-security/wildfly-elytron/pull/657
Based on https://github.com/wildfly-security/elytron-subsystem/pull/382
https://issues.jboss.org/browse/WFLY-8030

[WFLY-8030] LdapRealm referral loop test

---

src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
src/main/java/org/wildfly/extension/elytron/TlsParser.java
src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
src/main/resources/schema/wildfly-elytron_1_0.xsd
src/test/java/org/wildfly/extension/elytron/CredentialStoreUtility.java
src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
src/test/resources/org/wildfly/extension/elytron/tls-test.xml

Added alias-filter into key-manager and trust-manager.
https://issues.jboss.org/browse/WFLY-7158

[WFLY-7158] key-manager/trust-manager - alias-filter

---

src/main/java/org/wildfly/extension/elytron/CredentialStoreAliasDefinition.java

Elytron Subsystem: https://issues.jboss.org/browse/WFLY-8106

[WFLY-8106] Coverity static analysis, Dereference null return value,CredentialStoreAliasDefinition (elytron-subsystem)

---

src/main/java/org/wildfly/extension/elytron/CredentialStoreResource.java

We should go the all aliases to lower case way.
https://issues.jboss.org/browse/WFLY-8131
https://issues.jboss.org/browse/JBEAP-8871

Handling aliases - all to lower case
